---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sshd
  labels:
    app: sshd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sshd
  template:
    metadata:
      labels:
        app: sshd
    spec:
      hostNetwork: true
      containers:
      - name: sshd
        image: docker.io/linuxserver/openssh-server:latest
        env:
        - name: USER_PASSWORD
          value: aoeuaoeu
        volumeMounts:
        - name: cni-bin
          mountPath: /opt/cni/bin
        - name: cni-state
          mountPath: /var/run/azure-vnet.json
      volumes:
      - name: cni-bin
        hostPath:
          path: /opt/cni/bin
          type: Directory
      - name: cni-state
        hostPath:
          path: /var/run/azure-vnet.json
          type: File
