# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "daily"
  assigees:
    - "matmerr"
    - "rbtr"
  reviewers:
    - "azure/azure-sdn-members"
  commit-message:
    prefix: "deps"
- package-ecosystem: "gomod"
  directory: "/build/tools"
  schedule:
    interval: "daily"
  assigees:
    - "matmerr"
    - "rbtr"
  reviewers:
    - "azure/azure-sdn-members"
  commit-message:
    prefix: "deps"
- package-ecosystem: "gomod"
  directory: "/zapai"
  schedule:
    interval: "daily"
  assigees:
    - "matmerr"
    - "rbtr"
  reviewers:
    - "azure/azure-sdn-members"
  commit-message:
    prefix: "deps"
