---
apiVersion: v1
kind: Service
metadata:
  name: toolbox
spec:
  type: LoadBalancer
  selector:
    app: toolbox
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: matmerr-http-v4
spec:
  type: LoadBalancer
  selector:
    app: matmerr-http-v4
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: toolbox
  labels:
    app: toolbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: toolbox
  template:
    metadata:
      labels:
        app: toolbox
    spec:
      nodeSelector:
        kubernetes.io/role: agent
      containers:
        - name: toolbox
          image: acnpublic.azurecr.io/toolbox:latest
          env:
            - name: TCP_PORT
              value: "8085"
            - name: UDP_PORT
              value: "8086"
            - name: HTTP_PORT
              value: "8081"
          ports:
            - containerPort: 8081
