apiVersion: v1
kind: Config
clusters:
- name: kubernetes
  cluster:
    certificate-authority-data: <ca>
    <server>
contexts:
- name: azure-cns-win@kubernetes
  context:
    cluster: kubernetes
    namespace: kube-system
    user: azure-cns-win
current-context: azure-cns-win@kubernetes
users:
- name: azure-cns-win
  user:
    token: <token>
