name: golangci-lint
on:
  workflow_dispatch:
  pull_request:
jobs:
  golangci:
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.18.x]
        os: [ubuntu-latest, windows-latest]
    name: Lint
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }} 
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.45.2
        args: --timeout=10m 
        only-new-issues: true
